#!/usr/bin/env zsh

# This is my build script, but it is **heavily** dependent on environment, tools
# installed etc. So it's provided just for information/entertainment. Don't
# expect it to work on your system.

CODE_VERSION="5.3.3"
WRITE_ROM=0
WRITE_FLASH=0
WRITE_McROM=0
IMGFILE="EEPROM"
SUFFIX=""

usage()
{
    echo "Error: Unknown option."
    echo "Usage: build [-i | -w | -f]"
    echo "    -i Build 16K image only"
    echo "    -w Write to EEPROM after building"
    echo "    -f Write 16K image to Flash ROM after building"
    # echo "    -m Write 16K image to McROM after building"
}

while [ "$1" != "" ]; do
    case $1 in
        -f )    WRITE_FLASH=1
                IMGFILE="FLASH"
                SUFFIX="-16K"
                ;;
        -i )    IMGFILE="FLASH"
                SUFFIX="-16K"
                ;;
        -m )    WRITE_McROM=1
                IMGFILE="FLASH"
                SUFFIX="-16K"
                ;;
        -w )    WRITE_ROM=1
                ;;
        * )     usage
                exit 1
    esac
    shift
done

echo "Assembling z64-main.asm..."
OBJECT_FILE="bin/z64-ROM-${CODE_VERSION}${SUFFIX}.bin"
OUTPUT_TEXT="output/output-${CODE_VERSION}${SUFFIX}.txt"

echo "beebasm -v -i z64-main.asm -o ${OBJECT_FILE} -S VSTR=${CODE_VERSION} -S IMGFILE=${IMGFILE} -d -labels output/_labels.swift > ${OUTPUT_TEXT}"
beebasm -v -i z64-main.asm -o ${OBJECT_FILE} -S VSTR=${CODE_VERSION} -S IMGFILE=${IMGFILE} -d -labels output/_labels.swift > ${OUTPUT_TEXT}

cp ${OBJECT_FILE} bin/ROM.bin
if [ ${IMGFILE} = "FLASH" ]; then
    cp ${OBJECT_FILE} ~/Dev/Dev-STM/Workspaces/McROM/Debug/rom.bin
    cp ${OBJECT_FILE} ~/Dev/Dev-C/Zem/Zem/ROM/ROM.bin
    cp ${OBJECT_FILE} bin/ROM-16K.bin
fi

# Get return code of last command
result=$?

if [ $result -eq 0 ]; then
    echo "- created binary file : bin/z64-ROM-${CODE_VERSION}${SUFFIX}.bin"
    echo "- saved Beebasm output: output/output-${CODE_VERSION}${SUFFIX}.txt"
    output/labels.py
    cp output/os_functions.txt ../DOCUMENTATION
    if [ $WRITE_ROM -eq 1 ]; then
        echo "Writing to EEPROM..."
        echo "- minipro -p AT28C256 -w bin/z64-ROM-${CODE_VERSION}${SUFFIX}.bin"
        minipro -u -p AT28C256 -w bin/z64-ROM-${CODE_VERSION}${SUFFIX}.bin
    elif [ $WRITE_FLASH -eq 1 ]; then
        echo "Flashing ROM"
        ./flashz.py
    elif [ $WRITE_McROM -eq 1 ]; then
        # Hmmmmm.........
        # CD to project Debug dir
        # run make all
        # Then what?
    fi
else
    echo "*** ERROR *** Code failed to assemble. Huh."
    echo "Exit code: $result"
    exit 1
fi

exit 0
