#!/usr/bin/env bash
CODE_VERSION="06-dev"
WRITE_ROM=1

usage()
{
    echo "Error: Unknown option."
    echo "Usage: build [[-v version] [-b]]"
    echo " -b                  build only. Don't attempt to write to EEPROM"
    echo " -v <code_version>   build this version - z64-<code_version>.asm"
}

while [ "$1" != "" ]; do
    case $1 in
        -v )    shift
                CODE_VERSION="$1"
                ;;
        -b )    WRITE_ROM=0
                ;;
        * )     usage
                exit 1
    esac
    shift
done

echo "Assembling z64-${CODE_VERSION}.asm..."
echo "- creating binary file z64-ROM-${CODE_VERSION}.bin"
beebasm -v -i z64-${CODE_VERSION}.asm > output-${CODE_VERSION}.txt

# Get return code of last command
result=$?

if [ $WRITE_ROM -eq 1 ]; then
    if [ $result -eq 0 ]; then
        echo "Writing to EEPROM..."
        echo "- using minipro -p AT28C256 -w z64-ROM-${CODE_VERSION}.bin"
        minipro -p AT28C256 -w z64-ROM-${CODE_VERSION}.bin
    else
	    echo "*** ERROR *** Code failed to assemble. Huh."
        exit 1
    fi
fi

exit 0
