#!/usr/bin/env bash
PROG=${PWD##*/}          # Get name of current directory
PROG=${PROG:-/}          # Adjust for case where = /

UPLOAD=0

usage()
{
    echo "Error: Unknown option."
    echo "Usage: build [-u]"
    echo "    -u  Upload to RPi"
}

while [ "$1" != "" ]; do
    case $1 in
        -u )    UPLOAD=1
                ;;
        * )     usage
                exit 1
    esac
    shift
done

echo "Assembling $PROG.asm to $PROG.BIN"
beebasm -v -i ${PROG}.asm > ${PROG}_out.txt

result=$?

if [ $result -eq 0 ]; then
    if [ $UPLOAD -eq 1 ]; then    
		echo "Uploading to Imp..."
		scp -i ~/.ssh/ssh-key ../bin/$PROG.BIN pi@10.0.30.90:zd_files/$PROG.BIN
	fi
fi
