#!/usr/bin/env bash
CODE_VERSION="dev"

usage()
{
    echo "Error: Unknown option."
    echo "Usage: build [-v version]"
    echo "    -v <code_version>    write this version - z64-<code_version>.asm"
}

while [ "$1" != "" ]; do
    case $1 in
        -v )    shift
                CODE_VERSION="$1"
                ;;
        * )     usage
                exit 1
    esac
    shift
done


echo "Writing to EEPROM..."
echo "- minipro -p AT28C256 -w bin/z64-ROM-${CODE_VERSION}.bin"
minipro -p AT28C256 -w bin/z64-ROM-${CODE_VERSION}.bin

exit 0
