#!/usr/bin/env bash

APPS=("KEYB" "SETDATE" "SETTIME" "SRAM" "TS" "ZUMPUS" "LCDRST")

TARGET_HOST="zd0"

# Process command line options
while [ -n "$1" ]; do
	case "$1" in
		-h | --host)
			if [ -n "$2" ]; then
				TARGET_HOST=$2
				shift
				isIn $TARGET_HOST ${VALID_HOSTS[@]}
				if [[ $? -ne 1 ]]; then
					ERRORMSG="Not a valid host name."
					ERROR=2
				fi
			else
				ERRORMSG="Host name not supplied."
				ERROR=3
			fi;;
		*)	# this will deal with anything not in the options above
			ERRORMSG="$1 is not an option. Usage: zapp [-h|--host <hostname>]"
			ERROR=1;;
	esac
	shift		# move next param into $1
done


for APP in ${APPS[*]}; do
	echo "Building $APP..."
	cd $APP
	zapp -h $TARGET_HOST
	cd ..
done
