#!/usr/bin/env bash

APPS=("CLK" "INPUT" "IRQ" "MATH" "MATHTEST" "PRTFILE" "PRTTEST" "SRAM" "SETALARM" "SETDATE" "SETTIME" "TESTA" "TESTIO" "TIME" "ZUMPUS")

for APP in ${APPS[*]}; do
	echo "Building $APP..."
	cd $APP
	zapp
	cd ..
done
