#!/usr/bin/env bash

APPS=("CLK" "INPUT" "MATH" "MATHTEST" "PRTFILE" "PRTTEST" "SRAM" "SETTIME" "TESTA" "TESTIO" "TIME" "ZUMPUS")


for APP in ${APPS[*]}; do
	echo "Building $APP..."
	cd $APP
	zapp
	cd ..
done
